### ISSUE TITLE
Stack Trace on Login on Godot 3.4.2

### ISSUE THREAD

**Issue by finepointcgi** [StudioAdriatic/PGSGP#5]
Hey!
Im using this addon and everytime I try to login I get a stack trace saying its expecting an interface and got a class
```
12-29 12:00:31.036 19327 19327 D AndroidRuntime: Shutting down VM
12-29 12:00:31.037 19327 19327 E AndroidRuntime: FATAL EXCEPTION: main
12-29 12:00:31.037 19327 19327 E AndroidRuntime: Process: org.finepointcgi.gspp, PID: 19327
12-29 12:00:31.037 19327 19327 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.games.GamesClient, but interface was expected (declaration of 'com.google.android.gms.games.GamesClient' appears in /data/app/~~wB3kvUyirHWGIFARPNOpTQ==/org.finepointcgi.gspp-sTsf8cvrH5c50A2Gb7rwoA==/base.apk)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at io.cgisca.godot.gpgs.signin.SignInController.enablePopUps(SignInController.kt:104)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at io.cgisca.godot.gpgs.signin.SignInController.access$enablePopUps(SignInController.kt:12)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at io.cgisca.godot.gpgs.signin.SignInController$signIn$1.onComplete(SignInController.kt:52)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-29 12:00:31.037 19327 19327 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
I do end up getting my login in so the code itself seems to work however it always crashes on me or I get an error 10 depending on how the codes mood is.

Im using Godot 3.4 with Java 11

**Comment by finepointcgi** [comment]
It looks like if you disable popup it will not trigger this issues, however if I fire off and achievement I get another crash and stacktrace
```
12-29 12:39:03.109 21427 21427 E AndroidRuntime: FATAL EXCEPTION: main
12-29 12:39:03.109 21427 21427 E AndroidRuntime: Process: org.finepointcgi.gspp, PID: 21427
12-29 12:39:03.109 21427 21427 E AndroidRuntime: java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.games.AchievementsClient, but interface was expected (declaration of 'com.google.android.gms.games.AchievementsClient' appears in /data/app/~~-5Qt9kLPsIBqWOJhjI5VSw==/org.finepointcgi.gspp-WpugocuKF66A0L06MHyN1w==/base.apk)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at io.cgisca.godot.gpgs.achievements.AchievementsController.unlockAchievement(AchievementsController.kt:24)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at io.cgisca.godot.gpgs.PlayGameServicesGodot$unlockAchievement$1.run(PlayGameServicesGodot.kt:244)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7842)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-29 12:39:03.109 21427 21427 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by finepointcgi** [comment]
Yes im using that.
This is still an issue however I figured out how to get it all to work. 
You need to make sure you have both web and android authentication on your app. 
![image](https://user-images.githubusercontent.com/12012300/147698115-9a49bf1e-1eed-44c6-954a-44c41ccc1cac.png)
and make sure you have both authes in your app 
![image](https://user-images.githubusercontent.com/12012300/147698190-e96ce919-3980-4234-9156-2f3a58ffca79.png)

BE SURE TO PUBLISH THEM OR IT WILL NOT WORK

Finally be sure to set your token in the code the read me says nothing of this but it will cause a full crash on your app causing this stack trace
![image](https://user-images.githubusercontent.com/12012300/147698281-dffb323e-9f7b-4ae1-8c39-007f13abee9a.png)
The client id is the WEB not the android one it does not specify it in the readme.

**Comment by kristijandraca** [comment]
> #The client id must be created in [the google console](https://console.cloud.google.com/apis/credentials), an OAuth 2.0 Client credentials of a Web application type

This is from https://github.com/StudioAdriatic/PGSGP/wiki/Godot-Setup

maybe I need to add a special warning about this?

**Comment by olgam4** [comment]
I have followed that exact setup since I was having the same issues... But I'm still getting the same errors.

Is there something else that needs to be done?
